schemaVersion: 2.2.0
metadata:
  generateName: devspaces-quarkus-heloworld
attributes:
  controller.devfile.io/storage-type: per-workspace
  perUserStrategyPvcConfig:
    claimSize: 10Gi
  perWorkspaceStrategyPvcConfig:
    claimSize: 5Gi
components:
  - name: tools
    container:
      image: quay.io/devfile/universal-developer-image:ubi8-8627963
      env:
        - name: QUARKUS_HTTP_HOST
          value: 0.0.0.0
      endpoints:
        - exposure: none
          name: debug
          protocol: tcp
          targetPort: 5005
        - exposure: none
          name: test
          protocol: http
          targetPort: 8081
        - exposure: public
          name: inventory
          protocol: http
          targetPort: 8080
          path: /
      memoryRequest: 500Mi
      memoryLimit: 2G
      cpuRequest: 100m
      cpuLimit: 500m
      mountSources: true
      sourceMapping: /projects
      volumeMounts:
        - name: m2
          path: /home/user/.m2
  - name: m2
    volume:
      size: 2G
commands:
  - id: deploy
    exec:
      label: "1. Deploy"
      component: tools
      commandLine: |
        source $HOME/.sdkman/bin/sdkman-init.sh && \
        oc project $(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace) && \
        mvn clean package
      workingDir: ${PROJECT_SOURCE}
  - id: show-cluster-url
    exec:
      label: "2. Show Cluster URL"
      component: tools
      commandLine: |
        oc whoami --show-console
      workingDir: ${PROJECT_SOURCE}
  - id: quarkus-dev
    exec:
      label: "3. Start Development Mode"
      component: tools
      commandLine: |
        source $HOME/.sdkman/bin/sdkman-init.sh && \
        mvn -pl br.com.smanager:devspaces-quarkus-heloworld quarkus:dev
      workingDir: ${PROJECT_SOURCE}
  - id: cleanup
    exec:
      label: "4. Clean Up"
      component: tools
      commandLine: |
        oc delete all --selector app=devspaces-quarkus-heloworld
      workingDir: ${PROJECT_SOURCE}
events:
  postStart:
    - show-cluster-url